manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 684c9e8f32e4373a21098559f748f06915f950c9
      import:
        name-allowlist: [cmsis_6, hal_stm32]
  self:
    path: x-can
