#ifndef MCUBOOT_CONFIG_H
#define MCUBOOT_CONFIG_H

#define MCUBOOT_IMAGE_NUMBER 1
#define MCUBOOT_SWAP_USING_OFFSET 1
#define MCUBOOT_BOOTSTRAP 1
#define MCUBOOT_SIGN_EC256 1
#define MCUBOOT_USE_TINYCRYPT 1
#define MCUBOOT_VALIDATE_PRIMARY_SLOT 1
#define MCUBOOT_USE_FLASH_AREA_GET_SECTORS 1
#define MCUBOOT_BOOT_MAX_ALIGN 8
#define MCUBOOT_MAX_IMG_SECTORS 26
#define MCUBOOT_FIH_PROFILE_OFF 1
#define MCUBOOT_HAVE_ASSERT_H 1
#define MCUBOOT_DEV_WITH_ERASE 1
#define MCUBOOT_WATCHDOG_FEED() do { } while (0)
#define MCUBOOT_CPU_IDLE() do { } while (0)

#endif
