#pragma once
#define CONFIG_USB_PRINTF(...) ((void)0)
#define CONFIG_USB_DBG_LEVEL (-1)
#define CONFIG_USB_ALIGN_SIZE 4
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 256
#define CONFIG_USBDEV_MAX_BUS 1
#define CONFIG_USBDEV_FSDEV_PMA_ACCESS 1
/* Only 320 bytes needed: BTABLE + EP0 OUT/IN + bulk OUT/IN. */
#define CONFIG_USB_FSDEV_RAM_SIZE 512
#define USB_NOCACHE_RAM_SECTION
