CONFIG_XCAN_CAN=y
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_STATS=y
CONFIG_CAN_ACCEPT_RTR=y
CONFIG_CAN_MANUAL_RECOVERY_MODE=y
CONFIG_CAN_RX_TIMESTAMP=n
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_CAN_LOG_LEVEL_ERR=y
