CONFIG_XCAN_USB=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_MAX_SPEED_FULL=y
CONFIG_USBD_BOS_SUPPORT=y
CONFIG_USBD_VREQ_SUPPORT=y
CONFIG_UDC_STM32_CLOCK_CHECK=y
CONFIG_USBD_HWINFO_DEVID_LENGTH=12
CONFIG_USBD_THREAD_STACK_SIZE=1536
